export const AUTHECTICATION_PENDING="AUTHECTICATION_PENDING";
export const AUTHECTICATION_FAILED = "AUTHECTICATION_FAILED";
export const AUTHECTICATION_SUCCESS = "AUTHECTICATION_SUCCESS";
export const LOGOUT = "LOGOUT";


export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";